-- Orphaned object cleanup for mingster.com
-- Generated by the strip-to-three-features cleanup.
--
-- These tables/views back Prisma models that no longer exist in
-- prisma/schema.prisma. Reviewed and confirmed: mingster.com uses its OWN
-- database, separate from riben.life.
--
--   !! DO NOT RUN THIS UNTIL YOU HAVE A VERIFIED BACKUP !!
--
--   pg_dump "$DATABASE_URL" -Fc -f mingster-pre-cleanup-$(date +%Y%m%d).dump
--   pg_restore -l mingster-pre-cleanup-*.dump | head    # verify it is readable
--
-- Then run inside a transaction so you can bail out:
--   psql "$DATABASE_URL" -1 -f prisma/drop-orphaned-tables.sql
--
-- Recommended: run the SELECT block first to see what you are about to lose.

BEGIN;

-- ---------------------------------------------------------------------------
-- STEP 1 (read-only): row counts for everything about to be dropped.
-- Run this alone first. If any table you care about is non-empty, stop.
-- ---------------------------------------------------------------------------
/*
  SELECT 'Address' AS table_name, count(*) AS rows FROM "Address"
UNION ALL
  SELECT 'Category' AS table_name, count(*) AS rows FROM "Category"
UNION ALL
  SELECT 'CategoryLocale' AS table_name, count(*) AS rows FROM "CategoryLocale"
UNION ALL
  SELECT 'ContactUs' AS table_name, count(*) AS rows FROM "ContactUs"
UNION ALL
  SELECT 'Country' AS table_name, count(*) AS rows FROM "Country"
UNION ALL
  SELECT 'CreditBonusRule' AS table_name, count(*) AS rows FROM "CreditBonusRule"
UNION ALL
  SELECT 'Currency' AS table_name, count(*) AS rows FROM "Currency"
UNION ALL
  SELECT 'CustomerCredit' AS table_name, count(*) AS rows FROM "CustomerCredit"
UNION ALL
  SELECT 'CustomerCreditLedger' AS table_name, count(*) AS rows FROM "CustomerCreditLedger"
UNION ALL
  SELECT 'CustomerFiatLedger' AS table_name, count(*) AS rows FROM "CustomerFiatLedger"
UNION ALL
  SELECT 'CustomerInvite' AS table_name, count(*) AS rows FROM "CustomerInvite"
UNION ALL
  SELECT 'FacilityPricingRule' AS table_name, count(*) AS rows FROM "FacilityPricingRule"
UNION ALL
  SELECT 'FacilityServiceStaffPricingRule' AS table_name, count(*) AS rows FROM "FacilityServiceStaffPricingRule"
UNION ALL
  SELECT 'Faq' AS table_name, count(*) AS rows FROM "Faq"
UNION ALL
  SELECT 'FaqCategory' AS table_name, count(*) AS rows FROM "FaqCategory"
UNION ALL
  SELECT 'FaqCategoryLocale' AS table_name, count(*) AS rows FROM "FaqCategoryLocale"
UNION ALL
  SELECT 'FaqLocale' AS table_name, count(*) AS rows FROM "FaqLocale"
UNION ALL
  SELECT 'MessageQueue' AS table_name, count(*) AS rows FROM "MessageQueue"
UNION ALL
  SELECT 'NotificationChannelConfig' AS table_name, count(*) AS rows FROM "NotificationChannelConfig"
UNION ALL
  SELECT 'NotificationDeliveryStatus' AS table_name, count(*) AS rows FROM "NotificationDeliveryStatus"
UNION ALL
  SELECT 'NotificationPreferences' AS table_name, count(*) AS rows FROM "NotificationPreferences"
UNION ALL
  SELECT 'OrderItem' AS table_name, count(*) AS rows FROM "OrderItem"
UNION ALL
  SELECT 'OrderNote' AS table_name, count(*) AS rows FROM "OrderNote"
UNION ALL
  SELECT 'OrderRound' AS table_name, count(*) AS rows FROM "OrderRound"
UNION ALL
  SELECT 'PaymentMethod' AS table_name, count(*) AS rows FROM "PaymentMethod"
UNION ALL
  SELECT 'PlatformFaq' AS table_name, count(*) AS rows FROM "PlatformFaq"
UNION ALL
  SELECT 'PlatformFaqCategory' AS table_name, count(*) AS rows FROM "PlatformFaqCategory"
UNION ALL
  SELECT 'PlatformFaqCategoryLocale' AS table_name, count(*) AS rows FROM "PlatformFaqCategoryLocale"
UNION ALL
  SELECT 'PlatformFaqLocale' AS table_name, count(*) AS rows FROM "PlatformFaqLocale"
UNION ALL
  SELECT 'Product' AS table_name, count(*) AS rows FROM "Product"
UNION ALL
  SELECT 'ProductAttribute' AS table_name, count(*) AS rows FROM "ProductAttribute"
UNION ALL
  SELECT 'ProductCategories' AS table_name, count(*) AS rows FROM "ProductCategories"
UNION ALL
  SELECT 'ProductImages' AS table_name, count(*) AS rows FROM "ProductImages"
UNION ALL
  SELECT 'ProductLocale' AS table_name, count(*) AS rows FROM "ProductLocale"
UNION ALL
  SELECT 'ProductOption' AS table_name, count(*) AS rows FROM "ProductOption"
UNION ALL
  SELECT 'ProductOptionSelections' AS table_name, count(*) AS rows FROM "ProductOptionSelections"
UNION ALL
  SELECT 'ProductRelatedProduct' AS table_name, count(*) AS rows FROM "ProductRelatedProduct"
UNION ALL
  SELECT 'ReserveWithGoogleConversionEvent' AS table_name, count(*) AS rows FROM "ReserveWithGoogleConversionEvent"
UNION ALL
  SELECT 'ReserveWithGoogleFeedRun' AS table_name, count(*) AS rows FROM "ReserveWithGoogleFeedRun"
UNION ALL
  SELECT 'Rsvp' AS table_name, count(*) AS rows FROM "Rsvp"
UNION ALL
  SELECT 'RsvpBlacklist' AS table_name, count(*) AS rows FROM "RsvpBlacklist"
UNION ALL
  SELECT 'RsvpConversation' AS table_name, count(*) AS rows FROM "RsvpConversation"
UNION ALL
  SELECT 'RsvpConversationMessage' AS table_name, count(*) AS rows FROM "RsvpConversationMessage"
UNION ALL
  SELECT 'RsvpCustomerConfirmSent' AS table_name, count(*) AS rows FROM "RsvpCustomerConfirmSent"
UNION ALL
  SELECT 'RsvpReminderSent' AS table_name, count(*) AS rows FROM "RsvpReminderSent"
UNION ALL
  SELECT 'RsvpSettings' AS table_name, count(*) AS rows FROM "RsvpSettings"
UNION ALL
  SELECT 'RsvpTag' AS table_name, count(*) AS rows FROM "RsvpTag"
UNION ALL
  SELECT 'ServiceStaff' AS table_name, count(*) AS rows FROM "ServiceStaff"
UNION ALL
  SELECT 'ServiceStaffFacilitySchedule' AS table_name, count(*) AS rows FROM "ServiceStaffFacilitySchedule"
UNION ALL
  SELECT 'Shipment' AS table_name, count(*) AS rows FROM "Shipment"
UNION ALL
  SELECT 'ShippingMethod' AS table_name, count(*) AS rows FROM "ShippingMethod"
UNION ALL
  SELECT 'ShippingMethodPrice' AS table_name, count(*) AS rows FROM "ShippingMethodPrice"
UNION ALL
  SELECT 'StoreAnnouncement' AS table_name, count(*) AS rows FROM "StoreAnnouncement"
UNION ALL
  SELECT 'StoreAnnouncementLocale' AS table_name, count(*) AS rows FROM "StoreAnnouncementLocale"
UNION ALL
  SELECT 'StoreFacility' AS table_name, count(*) AS rows FROM "StoreFacility"
UNION ALL
  SELECT 'StoreFacilitySession' AS table_name, count(*) AS rows FROM "StoreFacilitySession"
UNION ALL
  SELECT 'StoreLedger' AS table_name, count(*) AS rows FROM "StoreLedger"
UNION ALL
  SELECT 'StoreOrder' AS table_name, count(*) AS rows FROM "StoreOrder"
UNION ALL
  SELECT 'StorePaymentMethodMapping' AS table_name, count(*) AS rows FROM "StorePaymentMethodMapping"
UNION ALL
  SELECT 'StoreProductOptionSelectionsTemplate' AS table_name, count(*) AS rows FROM "StoreProductOptionSelectionsTemplate"
UNION ALL
  SELECT 'StoreProductOptionTemplate' AS table_name, count(*) AS rows FROM "StoreProductOptionTemplate"
UNION ALL
  SELECT 'StoreSettings' AS table_name, count(*) AS rows FROM "StoreSettings"
UNION ALL
  SELECT 'StoreShipMethodMapping' AS table_name, count(*) AS rows FROM "StoreShipMethodMapping"
UNION ALL
  SELECT 'StoreSubscription' AS table_name, count(*) AS rows FROM "StoreSubscription"
UNION ALL
  SELECT 'StoreUserGoogleCalendarConnection' AS table_name, count(*) AS rows FROM "StoreUserGoogleCalendarConnection"
UNION ALL
  SELECT 'SubscriptionPayment' AS table_name, count(*) AS rows FROM "SubscriptionPayment"
UNION ALL
  SELECT 'SupportCannedReply' AS table_name, count(*) AS rows FROM "SupportCannedReply"
UNION ALL
  SELECT 'SupportTicket' AS table_name, count(*) AS rows FROM "SupportTicket"
UNION ALL
  SELECT 'SystemMessage' AS table_name, count(*) AS rows FROM "SystemMessage"
UNION ALL
  SELECT 'SystemMessageLocale' AS table_name, count(*) AS rows FROM "SystemMessageLocale"
UNION ALL
  SELECT 'SystemNotificationSettings' AS table_name, count(*) AS rows FROM "SystemNotificationSettings"
UNION ALL
  SELECT 'WaitList' AS table_name, count(*) AS rows FROM "WaitList"
UNION ALL
  SELECT 'WaitListSettings' AS table_name, count(*) AS rows FROM "WaitListSettings"
UNION ALL
  SELECT 'saved_product_customization' AS table_name, count(*) AS rows FROM "saved_product_customization"
  ORDER BY rows DESC, table_name;
*/

-- ---------------------------------------------------------------------------
-- STEP 2: drop views first (they depend on tables).
-- ---------------------------------------------------------------------------
DROP VIEW IF EXISTS "orderitemview" CASCADE;  -- model orderitemview

-- ---------------------------------------------------------------------------
-- STEP 3: drop tables. CASCADE clears FK constraints between them.
-- ---------------------------------------------------------------------------
DROP TABLE IF EXISTS "Address" CASCADE;
DROP TABLE IF EXISTS "Category" CASCADE;
DROP TABLE IF EXISTS "CategoryLocale" CASCADE;
DROP TABLE IF EXISTS "ContactUs" CASCADE;
DROP TABLE IF EXISTS "Country" CASCADE;
DROP TABLE IF EXISTS "CreditBonusRule" CASCADE;
DROP TABLE IF EXISTS "Currency" CASCADE;
DROP TABLE IF EXISTS "CustomerCredit" CASCADE;
DROP TABLE IF EXISTS "CustomerCreditLedger" CASCADE;
DROP TABLE IF EXISTS "CustomerFiatLedger" CASCADE;
DROP TABLE IF EXISTS "CustomerInvite" CASCADE;
DROP TABLE IF EXISTS "FacilityPricingRule" CASCADE;
DROP TABLE IF EXISTS "FacilityServiceStaffPricingRule" CASCADE;
DROP TABLE IF EXISTS "Faq" CASCADE;
DROP TABLE IF EXISTS "FaqCategory" CASCADE;
DROP TABLE IF EXISTS "FaqCategoryLocale" CASCADE;
DROP TABLE IF EXISTS "FaqLocale" CASCADE;
DROP TABLE IF EXISTS "MessageQueue" CASCADE;
DROP TABLE IF EXISTS "NotificationChannelConfig" CASCADE;
DROP TABLE IF EXISTS "NotificationDeliveryStatus" CASCADE;
DROP TABLE IF EXISTS "NotificationPreferences" CASCADE;
DROP TABLE IF EXISTS "OrderItem" CASCADE;
DROP TABLE IF EXISTS "OrderNote" CASCADE;
DROP TABLE IF EXISTS "OrderRound" CASCADE;
DROP TABLE IF EXISTS "PaymentMethod" CASCADE;
DROP TABLE IF EXISTS "PlatformFaq" CASCADE;
DROP TABLE IF EXISTS "PlatformFaqCategory" CASCADE;
DROP TABLE IF EXISTS "PlatformFaqCategoryLocale" CASCADE;
DROP TABLE IF EXISTS "PlatformFaqLocale" CASCADE;
DROP TABLE IF EXISTS "Product" CASCADE;
DROP TABLE IF EXISTS "ProductAttribute" CASCADE;
DROP TABLE IF EXISTS "ProductCategories" CASCADE;
DROP TABLE IF EXISTS "ProductImages" CASCADE;
DROP TABLE IF EXISTS "ProductLocale" CASCADE;
DROP TABLE IF EXISTS "ProductOption" CASCADE;
DROP TABLE IF EXISTS "ProductOptionSelections" CASCADE;
DROP TABLE IF EXISTS "ProductRelatedProduct" CASCADE;
DROP TABLE IF EXISTS "ReserveWithGoogleConversionEvent" CASCADE;
DROP TABLE IF EXISTS "ReserveWithGoogleFeedRun" CASCADE;
DROP TABLE IF EXISTS "Rsvp" CASCADE;
DROP TABLE IF EXISTS "RsvpBlacklist" CASCADE;
DROP TABLE IF EXISTS "RsvpConversation" CASCADE;
DROP TABLE IF EXISTS "RsvpConversationMessage" CASCADE;
DROP TABLE IF EXISTS "RsvpCustomerConfirmSent" CASCADE;
DROP TABLE IF EXISTS "RsvpReminderSent" CASCADE;
DROP TABLE IF EXISTS "RsvpSettings" CASCADE;
DROP TABLE IF EXISTS "RsvpTag" CASCADE;
DROP TABLE IF EXISTS "ServiceStaff" CASCADE;
DROP TABLE IF EXISTS "ServiceStaffFacilitySchedule" CASCADE;
DROP TABLE IF EXISTS "Shipment" CASCADE;
DROP TABLE IF EXISTS "ShippingMethod" CASCADE;
DROP TABLE IF EXISTS "ShippingMethodPrice" CASCADE;
DROP TABLE IF EXISTS "StoreAnnouncement" CASCADE;
DROP TABLE IF EXISTS "StoreAnnouncementLocale" CASCADE;
DROP TABLE IF EXISTS "StoreFacility" CASCADE;
DROP TABLE IF EXISTS "StoreFacilitySession" CASCADE;
DROP TABLE IF EXISTS "StoreLedger" CASCADE;
DROP TABLE IF EXISTS "StoreOrder" CASCADE;
DROP TABLE IF EXISTS "StorePaymentMethodMapping" CASCADE;
DROP TABLE IF EXISTS "StoreProductOptionSelectionsTemplate" CASCADE;
DROP TABLE IF EXISTS "StoreProductOptionTemplate" CASCADE;
DROP TABLE IF EXISTS "StoreSettings" CASCADE;
DROP TABLE IF EXISTS "StoreShipMethodMapping" CASCADE;
DROP TABLE IF EXISTS "StoreSubscription" CASCADE;
DROP TABLE IF EXISTS "StoreUserGoogleCalendarConnection" CASCADE;
DROP TABLE IF EXISTS "SubscriptionPayment" CASCADE;
DROP TABLE IF EXISTS "SupportCannedReply" CASCADE;
DROP TABLE IF EXISTS "SupportTicket" CASCADE;
DROP TABLE IF EXISTS "SystemMessage" CASCADE;
DROP TABLE IF EXISTS "SystemMessageLocale" CASCADE;
DROP TABLE IF EXISTS "SystemNotificationSettings" CASCADE;
DROP TABLE IF EXISTS "WaitList" CASCADE;
DROP TABLE IF EXISTS "WaitListSettings" CASCADE;
DROP TABLE IF EXISTS "saved_product_customization" CASCADE;  -- model SavedProductCustomization

-- ---------------------------------------------------------------------------
-- STEP 4: drop enum types that no longer have any column using them.
-- ---------------------------------------------------------------------------
DROP TYPE IF EXISTS "WaitListStatus" CASCADE;
DROP TYPE IF EXISTS "WaitlistSessionBlock" CASCADE;

-- ---------------------------------------------------------------------------
-- Verify the retained schema still matches Prisma, then commit.
--   \dt
-- Expected remaining tables: the 18 models in prisma/schema.prisma.
-- ---------------------------------------------------------------------------

-- COMMIT;   <-- uncomment deliberately, after reviewing the output above
ROLLBACK;    -- default: no-op so an accidental run changes nothing
